# Generated by Django 6.1 on 2026-09-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Drinks', 'Drinks'), ('Dresses', 'Dresses'), ('Beauty', 'Beauty'), ('Electronics', 'Electronics'), ('Shoes', 'Shoes'), ('Bags', 'Bags'), ('Home', 'Home'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
